version: '3'

services:
  gitlab:
    container_name: 'gitlab'
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:10080'
        nginx['listen_port'] = 10080
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
    ports:
      - '10080:10080'
      #- '10443:100443'
    volumes:
      - './data/gitlab/config:/etc/gitlab'
      - './data/gitlab/logs:/var/log/gitlab'
      - './data/gitlab/data:/var/opt/gitlab'
      #- '/etc/localtime:/etc/localtime:ro'
